### ISSUE TITLE
Can Lumia 950 be supported

### ISSUE THREAD

**Issue by DevPlus31** [SuperJMN/Lumia-WoA-Installer#5]
Hello 
I would like to know if Lumia 950 will be supported one day or not.

Thank you 

I really appreciate your effort.

**Comment by SuperJMN** [comment]
I'm currently working on it :)

**Comment by SuperJMN** [comment]
It's now supported! Check the latest release https://github.com/SuperJMN/Lumia-WoA-Installer/releases
